name: Generate Bitcoin Blog

on:
  schedule:
    - cron: "0 8 * * *"  # runs every day at 8:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ghp-import

      - name: Generate blog post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python bitcoin_blog_bot/generate_blog.py --categories bitcoin,ai,technology,ai-security

      - name: Commit blog to main branch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add _posts/
          git diff --cached --quiet || git commit -m "Daily blog update"
          git push https://x-access-token:${GH_TOKEN}@github.com/javivilchis/appsensechatbot.git HEAD:main

      - name: Tag the commit
        run: |
          DATE_TAG=$(date +'%Y-%m-%d')
          TAG_NAME="Generate Bitcoin Blog - $DATE_TAG"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f _posts -b gh-pages
