name: Generate Bitcoin Blog

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9am UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ghp-import

      - name: Generate blog post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_blog.py

      - name: Commit blog to main branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add _posts/
          git diff --cached --quiet || git commit -m "Weekly blog update"
          git push

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f _posts -b gh-pages